### ISSUE TITLE
Failed to open file TEfinder_20210228003051/*/*_DiscordantPairs.bam

### ISSUE THREAD

**Issue by AdamMajdi** [VistaSohrab/TEfinder#1]
I have been trying to run TEfinder. While the software works just fine using your example input data, it does not work with my real data. It gives the following error (I am including everything):

[bam_sort_core] merging from 329 files and 1 in-memory blocks...
Sun Feb 28 01:46:21 EST 2021  Alignment file sorted successfully.
Sun Feb 28 02:34:26 EST 2021  Alignments are filtered - secondary and supplementary alignments have been removed.
Sun Feb 28 02:34:26 EST 2021  Transposon analysis for Harbinger has started
Sun Feb 28 02:34:26 EST 2021  Transposon analysis for Hat has started
Sun Feb 28 02:34:26 EST 2021  Transposon analysis for Mariner has started
**mkdir: cannot create directory â€˜elementâ€™: File exists**
Sun Feb 28 02:34:26 EST 2021  Transposon analysis for Helitron has started
Sun Feb 28 02:34:26 EST 2021  Transposon analysis for isl2eu has started
Sun Feb 28 02:34:26 EST 2021  Transposon analysis for Bel has started
Sun Feb 28 02:34:26 EST 2021  Transposon analysis for Gypsy has started
Sun Feb 28 02:34:26 EST 2021  Transposon analysis for Copia has started
Sun Feb 28 02:34:26 EST 2021  Transposon analysis for Dirs has started
Sun Feb 28 02:34:26 EST 2021  Transposon analysis for Jockey has started
Sun Feb 28 02:34:26 EST 2021  Transposon analysis for L2 has started
Sun Feb 28 02:34:26 EST 2021  Transposon analysis for Loa has started
Sun Feb 28 02:34:26 EST 2021  Transposon analysis for L1 has started
Sun Feb 28 02:34:26 EST 2021  All transposons are processed. Finalizing...
**[E::hts_open_format] Failed to open file TEfinder_20210228003051/*/*_DiscordantPairs.bam
samtools merge: fail to open "TEfinder_20210228003051/*/*_DiscordantPairs.bam": No such file or directory**

**Interestingly:
Line 7: The folder "elementâ" was created
Last two lines: TEfinder_20210228003051 was created and I do see.**

**Comment by VistaSohrab** [comment]
Hi,

I have seen a similar error before when the TE list text file contains a carriage return character at the end of each line. If the TE list text file is created in Windows and transferred to Unix, carriage returns are introduced into the file which would need to be removed. The TE list text file can only have a newline character at the end of each line. I am not sure if the character encoding of the caret in elementâ may also be causing an issue, as seen with â€˜elementâ€™. 

The directories are generally created even though there may be invalid characters in the TE list input file, but the TEfinder intermediate files within the created TE directories are either empty or unable to be created.

**Comment by AdamMajdi** [comment]
Thank you for your reply. I have transformed the TE list file to UNIX format and I am running it again now. Regarding the directories, they have been created and they are not empty:

- alignmentInput.sorted.bam
- Alignments.bam
- reference.fa
- reference.fa.fai
- TEinsertions.bed
- userTE_noEmptyLines.txt

**Comment by AdamMajdi** [comment]
Now, I do not see the Error "**mkdir: cannot create directory â€˜elementâ€™: File exists**", but still have this error:

**[E::hts_open_format] Failed to open file TEfinder_20210228202527/*/*_DiscordantPairs.bam
samtools merge: fail to open "TEfinder_20210228202527/*/*_DiscordantPairs.bam": No such file or directory**

**Comment by VistaSohrab** [comment]
Could you provide the TE list and GTF files used in this run? 
Also, I am wondering whether any of the 14 or so TE directories created in TEfinder_20210228202527 contain non-empty intermediate files (if so, which files) to track where the error occurred.

**Comment by amendal** [comment]
Hi! The next error was produced. How can I fix it?

[E::hts_open_format] Failed to open file "TEfinder_20211130211916/*/*_DiscordantPairs.bam" : No such file or directory
samtools merge: fail to open "TEfinder_20211130211916/*/*_DiscordantPairs.bam": No such file or directory

**Comment by mvapontes** [comment]
Hi! any update on how to fix this error with a custom TE library?
Thanks!
